### ISSUE TITLE
Missing theme cat-A items

### ISSUE THREAD

**Issue by Consolatis** [labwc/labwc-scope#2]
- [ ] [menu.border.width](http://openbox.org/wiki/Help:Themes#menu.border.width)
- [x] [menu.separator.color](http://openbox.org/wiki/Help:Themes#menu.separator.color)
- [x] [menu.separator.width](http://openbox.org/wiki/Help:Themes#menu.separator.width)
- [ ] [menu.title.text.color](http://openbox.org/wiki/Help:Themes#menu.title.text.color)
- [x] [osd.border.color](http://openbox.org/wiki/Help:Themes#osd.border.color)
- [x] [osd.border.width](http://openbox.org/wiki/Help:Themes#osd.border.width)
- [ ] [window.active.button.hover.image.color](http://openbox.org/wiki/Help:Themes#window.active.button.hover.image.color)
- [ ] [window.active.button.pressed.image.color](http://openbox.org/wiki/Help:Themes#window.active.button.pressed.image.color)
- [ ] [window.handle.width](http://openbox.org/wiki/Help:Themes#window.handle.width)
- [ ] [window.inactive.button.hover.image.color](http://openbox.org/wiki/Help:Themes#window.inactive.button.hover.image.color)
- [ ] [window.inactive.button.pressed.image.color](http://openbox.org/wiki/Help:Themes#window.inactive.button.pressed.image.color)
- [ ] [window.inactive.handle.bg](http://openbox.org/wiki/Help:Themes#window.inactive.handle.bg)

Generated via
```bash
sed -n '/| 6\./ s|^.*[^`]*`\([^`]*\)`.*$|- [ ] [\1](http://openbox.org/wiki/Help:Themes#\1)| p' < incomplete-cat-A-items.md | sort
```

**Comment by johanmalm** [comment]
Remaining items have been demoted. All cat As now complete.
